nexmo/__init__.py, test_nexmo.py
This addresses #13 
Not sure this is really ready for merging. I'd like to add a test to see what happens when you attempt to, eg. send an SMS message without having key and secret set. I suspect the error will be a bit nasty and cryptic.
=> Made `key` and `secret` optional params for JWT-only Clients.

nexmo/__init__.py
changes to the api_key and api_secret params to allow users to create a client object without these parameters, for example when using the new VAPI api and authenticating with JWT key & secret are not required you just use the application_id and private key.
=> api_key & secret not mandatory

nexmo/__init__.py, test_nexmo.py
Fixes #12. Also adds a test to avoid breaking existing unspecified behaviour which is that keys can also be passed as RSAPrivateKey objects.
=> Support using file paths for private_key

.travis.yml, nexmo/__init__.py, test_nexmo.py
The assertRegexpMatches method was renamed to assertRegex in unittest 3.2
=> Use assertRegex instead of assertRegexpMatches

nexmo/__init__.py, test_nexmo.py
Fixes #15. Adds missing get_advanced_number_insight method, pointing to new endpoint. Adds get_standard_number_insight and deprecates get_number_insight for consistent naming.
=> Add method for Number Insight Advanced API

README.md
As the current Advance NI endpoint is in the released version, the GitHub README ought to reflect that.
Also changed the standard endpoint function call to use the non-deprecated call.
=> Adding Advance NI to README

nexmo/__init__.py
We have a requirement for a function to generate JWTs independent of making a request. This is a minimal implementation of that requirement for just application JWTs with no extra parameters.
=> Extract JWT generation code.

README.md
A number of the links also had duplicate query strings, so those have been fixed.
=> Repointed legacy docs links to developer.nexmo.com

setup.py
Installation of this package via pip could lead to outdated versions of dependent packages being used, which may result in unexpected or insecure behavior. `setup.py`'s `install_requires` has been updated to require minimum package versions.
This should close #38.
[Add versions for dependencies in setup.py](https://github.com/Nexmo/nexmo-python/issues/38)
Enhancement
All changes done in `setup.py`. The pinned versions should be verified.
=> Added minimum versions for dependencies.

setup.py
Adds `python_requires` in `setup.py` to avoid installing `nexmo-python` in python versions that are not supported.
=> Add a check to install nexmo only in supported Python versions.

README.md
I tried the code as is, and I got 400 error:
```
Client error: 400 b'{"type":400,"title":"Bad Request","invalid_parameters":[{"reason":"Invalid type parameter provided","name":"stream_url"}]}'
```
According to the docs, stream_url accepts an array of strings.
Changing the stream_url to a list works.
=> Readme: Update the code example for client.send_audio

README.md
nexmo-python works in Python 3, but print statement does not.
=> Use print functions in readme code examples instead of print statements

README.md
I found the documentation confusing at first.
I'm using Chrome browser on Mac OS (but I tested this behavior in Safari and Firefox too)
Initially, when I clicked on a link, eg the link to
https://developer.nexmo.com/api/voice#createCall?utm_source=DEV_REL&utm_medium=github&utm_campaign=python-client-library
I was redirected to the top of https://developer.nexmo.com/api/voice page, instead of the "Create an outbound call" section.
It would be nice if I was directed to the "Create an outbound call" section appropriately.
It turns out that the `#createCall` part needs to be placed at the end, after all of `?utm_source...`.
I updated all other urls.
=> Update the links in readme.

nexmo/__init__.py
Use session object instead of direct requests calls to allow
customization of the session, e.g. setting http proxy.
Fixes #128.
=> Use requests.Session for http calls

README.md
Simple overriding API url's instructions for users who otherwise don't have access to default url's
=> Adding Overriding API Url's Instructions

README.md
- Adding why we are dropping support for Python 2.7 and official statements and information.
=> Updates on dropping Python 2.7

src/vonage/__init__.py
Hi,
I was a bit confused when I compared the vonage.__version__ with the package's version number, and thought it would be natural to update the in-file version too.
=> Updated __version__ to match the release.

src/vonage/_internal.py
Max retries, pool connections, and pool maxsize arguments are very often used and adjusted within multi-threaded applications.
Currently in 2x vonage, max_retries is by default set to 0, which is not recommended for production-based applications since no retry mechanism is implemented. This leads to failures in multi-threaded environments. We set this variable to 3 and give option for users to set other arguments (they are optional and their default values are HTTPAdapter's default values).
=> Setting optional arguments such as : max retries, pool-connections, pool maxsize

src/vonage/client.py, tests/test_client.py
On Client a timeout parameter can be define in the `__init__` method This parameter is used to set `self.timeout` but is not used afterward.
This PR adds `self.timeout` each time `self.session` make a request
cf. https://requests.readthedocs.io/en/latest/user/quickstart/#timeouts
=> Add self.timeout on get/post/put and delete method of Client.session

.bumpversion.cfg, .gitignore, CHANGES.md, setup.py, src/vonage/__init__.py, src/vonage/messages.py
Bugfix in `messages.py` where authentication method was not being checked for correctly, throwing an error when using header auth.
=> Bugfix in messages.py

.bumpversion.cfg, .github/workflows/build.yml, CHANGES.md, Makefile, requirements.txt, setup.py, src/vonage/__init__.py, tests/test_account.py
I've added 3.11 to the github action that runs the tests, as well as removed some unnecessary dependencies.
=> Add support for Python 3.11

.github/workflows/build.yml, .github/workflows/mutation-test.yml, src/vonage/errors.py, src/vonage/number_insight.py, src/vonage/sms.py, src/vonage/verify.py, tests/data/number_insight/advanced_get.json, tests/data/number_insight/basic_get.json, tests/data/number_insight/get_async_error.json, tests/data/number_insight/get_error.json, tests/data/number_insight/standard_get.json, tests/data/sms/long_message.txt, tests/data/sms/send_long_message.json, tests/data/sms/send_long_message_partial_error.json, tests/data/sms/send_message_200_error.json, tests/data/verify/blocked_with_network.json, tests/data/verify/blocked_with_request_id.json, tests/data/verify/cancel_verification.json, tests/data/verify/check_verification.json, tests/data/verify/check_verification_error.json, tests/data/verify/control_verification_error.json, tests/data/verify/search_verification.json, tests/data/verify/search_verification_200_error.json, tests/data/verify/search_verification_multiple.json, tests/data/verify/start_verification.json, tests/data/verify/start_verification_error.json, tests/data/verify/trigger_next_event.json, tests/test_number_insight.py, tests/test_sms.py, tests/test_verify.py
This PR adds new exception classes, which are used in the case of APIs returning status 200 but there being an error. The Sms, Verify and NumberInsight classes have new methods and exceptions to deal with this situation.
This PR also adds the ability for a user to search for single or multiple verification requests by specifying either the `request` argument as a single string, or alternatively passing in a list of strings into the `request` argument.
=> Catching exceptions where the API returns with HTTP status 200

README.md, src/vonage/ncco_builder/ncco.py
This deprecates the Pay NCCO action as it's being removed from the Voice API. It will be removed in the next major release.
=> deprecating pay ncco action

src/vonage/errors.py
Historically we've subclassed a generic custom `Error` class. The exceptions related to use of the SDK should be subclasses of the `ClientError` exception, which is consistent with other Vonage server SDKs.
=> subclassing the ClientError class for SDK exceptions

src/vonage/client.py, src/vonage/number_management.py
The numbers api now uses header authentication instead of query parameter authentication.
Have added a type hint to the response to allow for easier debugging
Blackened the file
=> changing numbers API to use header authentication

src/vonage/ncco_builder/ncco.py, tests/test_ncco_builder/ncco_samples/ncco_action_samples.py, tests/test_ncco_builder/ncco_samples/ncco_builder_samples.py, tests/test_ncco_builder/test_ncco_actions.py, tests/test_ncco_builder/test_ncco_builder.py
This PR adds `advancedMachineDetection` to the NCCO builder. It's already possible in the SDK manually but this allows a user to use the feature in conjunction with the NCCO builder.
=> adding advancedMachineDetection to ncco builder and testing

.bumpversion.cfg, CHANGES.md, setup.py, src/vonage/__init__.py, src/vonage/verify2.py, tests/test_verify2.py
This updates `Verify2.new_request` so the `fraud_check` parameter is only sent in the request payload when specifically set to False.
=> Update fraud check

requirements.txt, setup.py, src/vonage/ncco_builder/connect_endpoints.py, src/vonage/ncco_builder/input_types.py, src/vonage/ncco_builder/ncco.py, src/vonage/ncco_builder/pay_prompts.py, src/vonage/subaccounts.py, src/vonage/verify2.py, tests/test_ncco_builder/ncco_samples/ncco_builder_samples.py, tests/test_ncco_builder/test_connect_endpoints.py, tests/test_ncco_builder/test_input_types.py, tests/test_ncco_builder/test_ncco_actions.py, tests/test_ncco_builder/test_ncco_builder.py, tests/test_verify2.py, tests/test_voice.py
I missed that someone else already had a PR open for this :( but I did manage to get all the tests passing with minimal changes, so I'm opening this in case it's helpful :)
=> Attempt to upgrade to pydantic 2

src/vonage/ncco_builder/connect_endpoints.py
When using the NCCO builder to create a Websocket Connect Endpoint, it serializes to have a field 'contentType', whilst the API expects a field of 'content-type'
{ "content-type": "...." }
{ "contentType": "...." }
```python
ws = ConnectEndpoints.WebsocketEndpoint(
uri=some_url,
contentType=f"audio/l{StreamingConfig.BITRATE};rate={StreamingConfig.FREQUENCY}"
)
c = Ncco.Connect(endpoint=ws, eventType="synchronous")
ncco = Ncco.build_ncco(c)
print(json.dumps(ncco, indent=4))
```
```json
[
{
"action": "connect",
"endpoint": [
{
"type": "websocket",
"uri": "wss://***.ngrok-free.app/ws",
"contentType": "audio/l16;rate=8000"
}
],
"eventType": "synchronous"
}
]
```
```json
{
"content-type": "audio/l16;rate=16000",
"event": "websocket:connected"
}
```
```json
{
"content-type": …
```
=> fix: change ncco websocket endpoint contentType to content-type

.bumpversion.cfg, .gitignore, CHANGES.md, setup.py, src/vonage/__init__.py, src/vonage/video.py, tests/test_video.py
- Add publisher-only as a valid Video API client token role
=> Add publisher only role

README.md
I think there is a typo in the example on how to transfer phone numbers between accounts.
=> fix a transfer phone number example in README

src/vonage/video.py
There was a slight discrepancy in specifying connection data. The accurate claim should be connection_data => 'name=Johnny', rather than 'data' => 'name=Johnny'
=> Modify claim "data" to "connection_data"
