nexmo/__init__.py, test_nexmo.py
Currently returning 400 Bad Request errors because request body should be JSON encoded instead of application/x-www-form-urlencoded.
=> Fix update_application method

README.md
We've got one for Ruby, we should have one for Python.
=> Documentation for Number Insight in README

docs/quickstart.rst, nexmo/__init__.py, tests/conftest.py, tests/test_nexmo.py
New PR based on #35 (conflicts resolved with up to date `develop` branch.)
=> Signing method

README.md
* Added info on how to update an installed client library.
* Added a doc entry for `get_recording`.
=> Show how to update library and add doc entry for get_recording.

CODE_OF_CONDUCT.md
I've used the generic support email address.
#Nextoberfest
=> Encourage more contributors for #Nextoberfest

setup.py
Hello,
I removed unused python modules.
what do you think?
Thanks.
=> Fix python unused modules

docs/quickstart.rst
Fixed some typos and grammatical errors
Contributed as a part of Hacktoberfest 2018
=> Fixed Typos and Grammatical Errors

README.md
Added badges:
- code style (black)
- supported python versions
:cake: :sparkles:
=> Add badges in README.md 

CHANGES.md
changed past tense sentences to present as the rest are also in present tense
=> Updated CHANGES.md to present tense

tests/test_misc.py, tests/test_redact.py
This PR adds a few more unit tests, some of which increase coverage.
=> Add a few more unit tests

nexmo/__init__.py, tests/conftest.py, tests/test_account.py
Brings the python lib in line with the other libraries, and fixes #123
=> Update User-Agent header format

README.md
Fix the link to the section within the table of contents
=> Fix link in table of contents

README.md
=> Add Number Management API usage examples to README

src/nexmo/__init__.py
=> Added get_async_advanced_number_insight method. callback is required

src/nexmo/__init__.py, src/nexmo/errors.py, tests/test_account.py, tests/test_sms.py, tests/test_voice.py
- Better error/exception handling
- Including tests
- Tested against current tests
=> Python sdk Exceptions/Error class

src/nexmo/__init__.py, src/nexmo/_internal.py
There didn't seem to be an existing way to pass a timeout on to the underlying requests calls so I've added a constructor argument to set the timeout
=> Add timeout to the client

README.md, src/nexmo/__init__.py, src/nexmo/_internal.py, src/nexmo/verify.py, tests/conftest.py, tests/test_nexmo.py, tests/test_verify.py
=> Create verify class

src/nexmo/__init__.py, src/nexmo/verify.py, tests/conftest.py, tests/test_verify.py
- Removing the voice, sms and verify methods from client
- Adding the verify class
- Adapting tests for the verify class
Test ran and it's working as expected
=> client cleanup and adding verify class

CONTRIBUTING.md
Solves #171 
Added a link to Documentation page.
It helps contributors to better understand the concepts behind Vonage's APIs
=> Added link to documentation

README.md
This is my first time contributing. Corrected few typos in method call names
Fixes Issue #184
=> Fixes Important Method name Typo

README.md
Signposting support for upcoming asyncio library
=> Signposting Asyncio Support

.github/workflows/build.yml, src/vonage/voice.py, tests/test_voice.py
- Added code in voice.py to reflect the random pool number
- Added test `test_params_with_random_number` 
Note: When I test on my phone I do get calls from random numbers but my test is not passing. Would love your feedback when you have some time.
=> added random_from_number to voice.py and added new test

README.md
=> Correct Documentation, replace request method by start_verification

src/vonage/_internal.py
=> set timeout from init method argument

.bumpversion.cfg, CHANGES.md, setup.py, src/vonage/__init__.py, tests/test_packages.py
This fixes the import issue with the ncco builder
=> Fix ncco error

src/vonage/errors.py
Removing an intermediary class that adds nothing
Blackening the file
=> removing redundant intermediary Error class

README.md
Updating README.md to link to all sections
=> adding links to all sections

.bumpversion.cfg, CHANGES.md, setup.py, src/vonage/__init__.py
Readies the code for a minor release
=> V3.4.0 release

.bumpversion.cfg, CHANGES.md, setup.py, src/vonage/__init__.py
Prepares the SDK for the v3.5.0 release
=> V3.5.0 release

.mend
Removes the false positive IAC checks as requested by Vonage IT
=> Add new .mend config
